// Generated by scripts/generate_atlas.py. Do not edit manually.
export const atlasData = {
  "project": {
    "name": "Kiro Atlas",
    "description": "Kiro Atlas is a Kiro hook challenge showcase that turns committed steering, specs, tasks, hooks, and source relationships into a polished Lakebed project-intelligence page. It demonstrates how one repository change can automatically produce meaningful, visible output for teammates, contributors, and the community.",
    "tagline": "Make the hidden .kiro workspace visible"
  },
  "steering": [
    {
      "name": "product.md",
      "path": ".kiro/steering/product.md",
      "title": "Quest Board Product",
      "summary": "Quest Board is a tiny fictional project for people learning Kiro. It lets a user create a quest, choose its difficulty, and mark it complete without hiding the idea behind production-scale architecture.",
      "headings": [
        "Audience",
        "Product goals"
      ],
      "bullets": [
        "Community members exploring a working Kiro workflow",
        "Developers trying Kiro for the first time",
        "Teams learning how steering and specs connect to source files",
        "Demo viewers who need a project they can understand in minutes",
        "Keep the Quest Board example deliberately small",
        "Make every Kiro artifact easy to inspect",
        "Use Kiro Atlas to make the workspace workflow visible",
        "Favor a clear teaching moment over extra features"
      ]
    },
    {
      "name": "structure.md",
      "path": ".kiro/steering/structure.md",
      "title": "Repository Structure",
      "summary": "The repository separates Kiro knowledge, fictional application code, generation logic, and the visual capsule so a new user can see each responsibility at a glance.",
      "headings": [
        "Directories",
        "Boundaries"
      ],
      "bullets": [
        "`.kiro/` contains steering, specs, and Kiro CLI hooks",
        "`demo/` contains the fictional Quest Board source files",
        "`scripts/` contains the Atlas generator",
        "`capsule/` contains the Lakebed homepage",
        "`capsule/shared/atlas.generated.ts` is generated and must not be edited manually",
        "Generated data contains repository-relative paths only",
        "The generator reads only its documented repository allowlist",
        "Demo files are educational samples, not a separate runnable product"
      ]
    },
    {
      "name": "tech.md",
      "path": ".kiro/steering/tech.md",
      "title": "Technical Direction",
      "summary": "Quest Board uses simple TypeScript files, while Kiro Atlas uses Lakebed and Preact for its visual homepage. A small Python standard-library generator connects the committed workspace artifacts to the page.",
      "headings": [
        "Technology choices",
        "Constraints"
      ],
      "bullets": [
        "TypeScript for the fictional Quest Board source files",
        "Lakebed and Preact for the Atlas homepage",
        "Tailwind utilities supplied by Lakebed for styling",
        "Python standard library only for data generation",
        "No database or application backend is needed",
        "No external APIs or frontend dependencies",
        "Keep code small, readable, and suitable for a one-day demo",
        "Deployment stays a deliberate manual command"
      ]
    }
  ],
  "specs": [
    {
      "name": "create-quests",
      "path": ".kiro/specs/create-quests",
      "hasRequirements": true,
      "hasDesign": true,
      "hasTasks": true,
      "requirementHeadings": [
        "Create a quest",
        "Complete a quest",
        "Keep the demo understandable"
      ],
      "designHeadings": [
        "Quest model",
        "In-memory store",
        "Error handling"
      ],
      "tasks": [
        {
          "text": "Define the Quest model in `demo/quests.ts`",
          "completed": true
        },
        {
          "text": "Add an in-memory store in `demo/quest-store.ts`",
          "completed": true
        },
        {
          "text": "Implement quest creation in `demo/quest-store.ts`",
          "completed": true
        },
        {
          "text": "Implement quest completion in `demo/quest-store.ts`",
          "completed": true
        }
      ],
      "completedTasks": 4,
      "incompleteTasks": 0,
      "firstIncompleteTask": null,
      "referencedFiles": [
        "demo/quest-store.ts",
        "demo/quests.ts"
      ]
    },
    {
      "name": "quest-difficulty",
      "path": ".kiro/specs/quest-difficulty",
      "hasRequirements": true,
      "hasDesign": true,
      "hasTasks": true,
      "requirementHeadings": [
        "Choose a difficulty",
        "Show a readable label",
        "Preserve simple types"
      ],
      "designHeadings": [
        "Difficulty type",
        "Quest integration",
        "Display helper"
      ],
      "tasks": [
        {
          "text": "Create the Difficulty type in `demo/difficulty.ts`",
          "completed": true
        },
        {
          "text": "Add difficulty to the Quest type in `demo/quests.ts`",
          "completed": true
        },
        {
          "text": "Add a helper that returns a readable difficulty label in `demo/difficulty.ts`",
          "completed": false
        }
      ],
      "completedTasks": 2,
      "incompleteTasks": 1,
      "firstIncompleteTask": "Add a helper that returns a readable difficulty label in `demo/difficulty.ts`",
      "referencedFiles": [
        "demo/difficulty.ts",
        "demo/quests.ts"
      ]
    }
  ],
  "hooks": [
    {
      "name": "Update Kiro Atlas",
      "description": "Regenerate public Atlas data after Kiro workspace, demo source, or project documentation edits.",
      "path": ".kiro/hooks/update-atlas.json",
      "trigger": "PostFileSave",
      "matcher": "(?:(?:\\.kiro|demo)/.+|README\\.md$)",
      "actionType": "command",
      "command": "python3 scripts/generate_atlas.py",
      "enabled": true
    },
    {
      "name": "Update Kiro Atlas after replacement edits",
      "description": "CLI v3 fallback for replacement edits that do not emit PostFileSave.",
      "path": ".kiro/hooks/update-atlas.json",
      "trigger": "PostToolUse",
      "matcher": "^str_replace$",
      "actionType": "command",
      "command": "python3 scripts/generate_atlas.py",
      "enabled": true
    }
  ],
  "projectFiles": [
    {
      "path": "demo/difficulty.ts",
      "name": "difficulty.ts",
      "extension": "ts",
      "symbols": [
        {
          "kind": "type",
          "name": "Difficulty"
        }
      ],
      "referencedBy": [
        "quest-difficulty"
      ]
    },
    {
      "path": "demo/quest-store.ts",
      "name": "quest-store.ts",
      "extension": "ts",
      "symbols": [
        {
          "kind": "class",
          "name": "QuestStore"
        }
      ],
      "referencedBy": [
        "create-quests"
      ]
    },
    {
      "path": "demo/quests.ts",
      "name": "quests.ts",
      "extension": "ts",
      "symbols": [
        {
          "kind": "type",
          "name": "Quest"
        },
        {
          "kind": "function",
          "name": "createQuest"
        }
      ],
      "referencedBy": [
        "create-quests",
        "quest-difficulty"
      ]
    }
  ],
  "summary": {
    "specs": 2,
    "steeringFiles": 3,
    "hooks": 2,
    "demoFiles": 3,
    "completedTasks": 6,
    "totalTasks": 7,
    "progressPercent": 86
  },
  "nextStep": {
    "spec": "quest-difficulty",
    "task": "Add a helper that returns a readable difficulty label in `demo/difficulty.ts`",
    "path": ".kiro/specs/quest-difficulty/tasks.md"
  }
};
